spring:
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq

        - id: product_route
          uri: lb://gulimall-product
          predicates:
            #商品服务都以"/api/product"开头
            - Path=/api/product/**
          filters:
            #理论上: http://localhost:88/api/product/category/list/tree -> http://localhost:8401/product/category/list/tree
            - RewritePath=/api(?<segment>/?.*), /$\{segment}

        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty(?<segment>/?.*), /$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
              #前端项目都以"/api"开头
            - Path=/api/**
          filters:
             #验证码请求,理论上: http://localhost:88/api/captcha.jpg -> http://localhost:8080/renren-fast/captcha.jpg
             #验证码请求,实际上: http://localhost:88/api/captcha.jpg -> http://localhost:8080/api/captcha.jpg
             #由于理论与实际的区别,所以需要进行路径重写
            - RewritePath=/api(?<segment>/?.*), /renren-fast/$\{segment}


